name: Deno

env:
  COSMOS_URL: ${{ secrets.COSMOS_URL }}
  COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
  MONGO_URL: ${{ secrets.MONGO_URL }}

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno lint

      - name: Install mongo
        run: docker run --name mongo-ci -p 27017:27017 -d mongo 

      - name: Run tests
        run: deno task test

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
