name: Deno

env:
  SENGI_COSMOS_URL: ${{ secrets.SENGI_COSMOS_URL }}
  SENGI_COSMOS_KEY: ${{ secrets.SENGI_COSMOS_KEY }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Setup cosmos
        run: deno task setup_cosmos

      - name: Run tests
        run: deno task test

      - name: Cleanup cosmos
        if: success() || failure()
        run: deno task teardown_cosmos
